-- TRANSACAO POR DIA DO CURDO (08-25 / 08-29) CRESCENTEMENTE

WITH TB_DAYS AS (
    SELECT
        SUBSTR(DtCriacao,1,10) AS DATE,
        COUNT(DISTINCT IdTransacao) AS TRANSACOES
    FROM transacoes

    WHERE SUBSTR(DtCriacao,1,10) >= '2025-08-25'
    AND SUBSTR(DtCriacao,1,10) < '2025-08-30'

    GROUP BY SUBSTR(DtCriacao,1,10)
),

ACUMULATION AS (
    SELECT *,
    SUM(TRANSACOES) OVER (PARTITION BY 1 ORDER BY DATE) AS ACUMULATION
    FROM TB_DAYS
)
 
SELECT *
FROM ACUMULATION