-- PONTOS ACUMULADO POR PESSOA

WITH TB_COUNT_TRA AS (
    SELECT 
        IdCliente,
        SUBSTR(DtCriacao,1,10) AS DATE,
        COUNT(DISTINCT IdTransacao) AS QUANTTRAN

    FROM transacoes
    WHERE DtCriacao >= '2025-08-25'
    AND DtCriacao < '2025-08-30'
    GROUP BY IdCliente,DATE
),

TB_ACUMULATION_LAG AS (
    SELECT *,
        SUM(QUANTTRAN) OVER (PARTITION BY IdCliente ORDER BY DATE) AS ACUMULATION,
        -- JOGA UMA LINHA PARA BAIXO
        LAG(QUANTTRAN) OVER (PARTITION BY IdCliente ORDER BY DATE) AS LAG
    FROM TB_COUNT_TRA
)

SELECT *,
    -- QUANTOS PORCENTOS MAIOR
    ROUND(1. *  QUANTTRAN / lag * 100, 2) AS PCT
FROM TB_ACUMULATION_LAG;
