-- DE QUANTO EM QUANTO TEMPO OS CLIENTES VOLTAM

WITH TB_CLIENT AS (
    SELECT 
        DISTINCT IdCliente,
        SUBSTR(DtCriacao,1,10) AS  DATE
    FROM TRANSACOES

    WHERE SUBSTR(DtCriacao,1,4) = '2025'
    ORDER BY IdCliente, DATE 
),

TB_LAG AS (
    SELECT *,
        LAG(DATE) OVER (PARTITION BY IdCliente ORDER BY DATE) AS LAG_DAY
    FROM TB_CLIENT
),

TB_DIFF_DAY AS (
    SELECT *,
        JULIANDAY(DATE) - JULIANDAY(LAG_DAY) AS DAY
    FROM TB_LAG
),

AVG_CLIENT AS (
    SELECT 
        IdClientE, 
        ROUND(AVG(DAY),2) AS DAY
    FROM TB_DIFF_DAY
    GROUP BY IdCliente

)

SELECT *
FROM AVG_CLIENT