
DROP TABLE IF EXISTS relatorio_diario;

CREATE TABLE IF NOT EXISTS relatorio_diario AS

WITH TB_DAYS AS (
    SELECT 
        SUBSTR(DtCriacao,1,10) AS DATE,
        COUNT(DISTINCT IdTransacao) AS ACUM
    FROM transacoes
    GROUP BY DATE
    ORDER BY DATE 
),

TB_ACUMULATION AS (
    SELECT *,
        SUM(ACUM) OVER (ORDER BY DATE ASC) AS CUMULATIVE_SUM
    FROM TB_DAYS
)

SELECT * 
FROM TB_ACUMULATION;



-- CRIEI UMA TABELA, É MAIS RAPIDO DO QUE SEMPRE EXECUTAR A QUARY ACIMA
-- POREM ELA É FIXA, NAO ATUALIZA NORMALMENTE
-- PRECISA APAGAR E SALVAR DNOVO

SELECT *
FROM relatorio_diario;

