
DELETE FROM relatorio_diario;

WITH TB_DAYS AS (
    SELECT 
        SUBSTR(DtCriacao,1,10) AS DATE,
        COUNT(DISTINCT IdTransacao) AS ACUM
    FROM transacoes
    GROUP BY DATE
    ORDER BY DATE 
),

TB_ACUMULATION AS (
    SELECT *,
        SUM(ACUM) OVER (ORDER BY DATE ASC) AS CUMULATIVE_SUM
    FROM TB_DAYS
)

-- INSERINDO DENTRO DE RELATORIO 
-- SO DEPOIS DE DELETAR, PQ SE NAO ELE DUPLICA A TABELA
INSERT INTO relatorio_diario

SELECT * 
FROM TB_ACUMULATION;

SELECT * FROM relatorio_diario;
