-- WHICH WEEK DAY HAVE MORE ORDER IN 2025
--BEST WAY
SELECT
    STRFTIME('%w',datetime(DtCriacao)) AS WEEK,
    -- SAME THING FOR BE ID (ID IS UNIC)
    COUNT(*) AS TOTAL,
    COUNT(DISTINCT IdTransacao) AS TOTAL2,
    COUNT(IdTransacao) AS TOTAL3

FROM transacoes

WHERE SUBSTR(DtCriacao, 1, 4) = '2025'

GROUP BY WEEK
-- SECOND LINE OF SELECT
ORDER BY 2 DESC
