-- CLIENTES MAIS ANTISOG, TEM MAIS FREQUENCIA E TRANCAÇÃO?

SELECT 
    DISTINCT T1.IdCliente,
    CAST(JULIANDAY('now') - JULIANDAY(SUBSTR(T1.DtCriacao,1,19)) AS INT) AS DATEBASE,
    COUNT(DISTINCT T2.IdTransacao) AS COUNT

FROM clientes AS T1

LEFT JOIN transacoes AS T2
    ON T1.IdCliente = T2.IdCliente

GROUP BY T1.idCliente, DATEBASE
ORDER BY CAST(JULIANDAY('now') - JULIANDAY(SUBSTR(T1.DtCriacao,1,19)) AS INT) DESC
