-- QUEM INICIOU O CURSO NO PRIMEIRO DIA, 
-- EM MEDIA ASSISTIU QUANTAS AULAS?

-- QUEM PARTICIPOU DA PRIMEIRA AULA
WITH TB_FIRST_DAY AS (
    SELECT DISTINCT IdCliente
    FROM transacoes
    WHERE SUBSTR(DtCriacao,1,10) = '2025-08-25'
),

-- QUEM PARTICIPOU DO CURSO TODO
TB_COURSE_DAY AS (
    SELECT DISTINCT
        IdCliente,
        SUBSTR(DtCriacao,1,10) AS DATE
    FROM transacoes
    WHERE SUBSTR(DtCriacao,1,10) >= '2025-08-25'
    AND SUBSTR(DtCriacao,1,10) < '2025-08-30'
    ORDER BY IdCliente,DATE
),

-- CONTANTO QUANTAS VEZES QUEM TAVA NO PRIMEIRO DIA VOLTOU
TB_JOIN AS (
    SELECT 
        T1.IdCliente,
        COUNT(DISTINCT T2.DATE) AS DAYS
    FROM TB_FIRST_DAY AS T1

    LEFT JOIN TB_COURSE_DAY AS T2
    ON T1.IdCliente = T2.IdCliente
    GROUP BY T1.IdCliente
)

-- CALCULA A MEDIA
SELECT 
    AVG(DAYS) AS AVG,
    MAX(DAYS) AS MAX,
    MIN(DAYS) AS MIN 
FROM TB_JOIN
