-- DENTRE OS CLIENTES DE JANEIRO/2025, QUANTOS ASSISTIRAM O CURSO DE SQL (08-25 - 08-29)

WITH TB_CLIENT_JAN AS (
    SELECT DISTINCT IdCliente
    FROM transacoes
    WHERE SUBSTR(DtCriacao,1,10) >= '2025-01-01'
    AND SUBSTR(DtCriacao,1,10) < '2025-02-01'
),

TB_CLIENT_COURSE AS (
    SELECT DISTINCT IdCliente
    FROM transacoes
    WHERE SUBSTR(DtCriacao,1,10) >= '2025-08-25'
    AND SUBSTR(DtCriacao,1,10) < '2025-08-30'
),

TB_JOIN AS (
    SELECT
        (SELECT COUNT(*) FROM TB_CLIENT_JAN) AS JAN,
        COUNT(DISTINCT T2.IdCliente) AS TOTAL
    FROM TB_CLIENT_JAN AS T1

    INNER JOIN TB_CLIENT_COURSE AS T2
    ON T1.IdCliente = T2.IdCliente
)

SELECT *
FROM TB_JOIN
