-- QUANTIDADE TRANSAÇOES ACUMULADAS AO LONGO DO TEMPO (DIARIO)

WITH TB_DAYS AS (
    SELECT 
        SUBSTR(DtCriacao,1,10) AS DATE,
        COUNT(DISTINCT IdTransacao) AS ACUM
    FROM transacoes
    GROUP BY DATE
    ORDER BY DATE 
),

TB_ACUMULATION AS (
    SELECT *,
        SUM(ACUM) OVER (ORDER BY DATE ASC) AS CUMULATIVE_SUM
    FROM TB_DAYS
)


-- QUANDO PEGOU 100K
SELECT * 
FROM TB_ACUMULATION
WHERE CUMULATIVE_SUM > 100000
ORDER BY CUMULATIVE_SUM 
LIMIT 1
