--  QUANTIDADE DE USUARIOS CADASTRADOS (ABSOLUTO E ACUMULADO) AO LONGO DO TEMPO (DIARIO)

WITH TB_CLIENT AS (
    SELECT
        SUBSTR(DtCriacao, 1, 10) AS DATE,
        COUNT(DISTINCT IdCliente) AS CLIENT
    FROM clientes
    GROUP BY DATE
    ORDER BY DATE ASC
),

TB_ACUMULATION AS (
    SELECT *,
        SUM(CLIENT) OVER (ORDER BY DATE ASC) AS CUMULATIVE_SUM
    FROM TB_CLIENT
)

-- quando atingiu mais de 3000 clientes
SELECT *
FROM TB_ACUMULATION
WHERE CUMULATIVE_SUM > 3000